# Permalinks
permalink:           pretty

# Setup
title:               "\"You know, I've learned something today...\""
tagline:             ""
home:                https://mirigmirig.github.io
url:                 https://mirigmirig.github.io/blog
paginate:            5
baseurl:             /blog
excerpt_separator: "<!--read more-->"


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
